#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: eOVPN\n"
"POT-Creation-Date: 2021-02-23 20:42+0530\n"
"PO-Revision-Date: 2021-02-17 16:04+0530\n"
"Last-Translator: Jagadeesh Kotra <jagadeesh.01101011@gmail.com>\n"
"Language-Team: \n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.4.2\n"
"X-Poedit-Basepath: ..\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-KeywordsList: __push_to_statusbar\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-SearchPath-0: eovpn\n"
"X-Poedit-SearchPath-1: data\n"
"X-Poedit-SearchPath-2: data/ui\n"
"X-Poedit-SearchPathExcluded-0: __pycache__/*\n"

#: data/com.github.jkotra.eovpn.desktop:3
#: data/com.github.jkotra.eovpn.desktop:4
msgid "eOVPN"
msgstr ""

#: data/com.github.jkotra.eovpn.desktop:5
msgid "OpenVPN Configuration Manager"
msgstr ""

#: data/ui/about.glade:12
msgid "OpenVPN Configuration(s) Manager"
msgstr ""

#: data/ui/log.glade:7 data/ui/main.glade:98
msgid "Log"
msgstr ""

#: data/ui/log.glade:50
msgid "Close"
msgstr ""

#: data/ui/main.glade:19
msgid "OpenVPN is running in background!"
msgstr ""

#: data/ui/main.glade:20
msgid ""
"OpenVPN is still running in background. It must be killed before attempting "
"to connect again. Kill it?"
msgstr ""

#: data/ui/main.glade:32 data/ui/settings.glade:784
msgid "Cancel"
msgstr ""

#: data/ui/main.glade:46
msgid "Kill"
msgstr ""

#: data/ui/main.glade:82
msgid "View Config"
msgstr ""

#: data/ui/main.glade:114
msgid "Update"
msgstr ""

#: data/ui/main.glade:132
msgid "Settings"
msgstr ""

#: data/ui/main.glade:150
msgid "About"
msgstr ""

#: data/ui/main.glade:168
msgid "Exit"
msgstr ""

#: data/ui/main.glade:205 eovpn/main_window.py:244
msgid "Disconnected"
msgstr ""

#: data/ui/main.glade:251
msgid "IP: 127.0.0.1"
msgstr ""

#: data/ui/main.glade:301
msgid "Location: Earth"
msgstr ""

#: data/ui/main.glade:389
msgid "TCP/UDP"
msgstr ""

#: data/ui/main.glade:463
msgid "OpenVPN configuration"
msgstr ""

#: data/ui/main.glade:489 eovpn/main_window.py:251
msgid "Connect!"
msgstr ""

#: data/ui/settings.glade:65
msgid "Undo"
msgstr ""

#: data/ui/settings.glade:129
msgid "Configuration Source: "
msgstr ""

#: data/ui/settings.glade:143
msgid "https://example.com/configs.zip"
msgstr ""

#: data/ui/settings.glade:155
msgid "Validate"
msgstr ""

#: data/ui/settings.glade:206
msgid "Requires Authentication"
msgstr ""

#: data/ui/settings.glade:234
msgid "Username:"
msgstr ""

#: data/ui/settings.glade:272
msgid "Password:"
msgstr ""

#: data/ui/settings.glade:314
msgid "Show Password"
msgstr ""

#: data/ui/settings.glade:337
msgid "Authentication"
msgstr ""

#: data/ui/settings.glade:359
msgid "OpenVPN CRT:"
msgstr ""

#: data/ui/settings.glade:434
msgid "Setup"
msgstr ""

#: data/ui/settings.glade:469
msgid "Notifications"
msgstr ""

#: data/ui/settings.glade:485
msgid "Send Notification on Connect AND Disconnect Event."
msgstr ""

#: data/ui/settings.glade:544
msgid "Update on Launch"
msgstr ""

#: data/ui/settings.glade:560
msgid "Update Configuration(s) from remote on launch."
msgstr ""

#: data/ui/settings.glade:619
msgid "Connect on Launch"
msgstr ""

#: data/ui/settings.glade:635
msgid "Connect to last connected config on Launch."
msgstr ""

#: data/ui/settings.glade:686
msgid "General"
msgstr ""

#: data/ui/settings.glade:720
msgid "Save"
msgstr ""

#: data/ui/settings.glade:732
msgid "Reset"
msgstr ""

#: data/ui/settings.glade:770
msgid "Are you sure?"
msgstr ""

#: data/ui/settings.glade:771
msgid "All settings will be permanently deleted."
msgstr ""

#: data/ui/settings.glade:799
msgid "Yes"
msgstr ""

#: eovpn/main_window.py:134
msgid "Failed to connect!"
msgstr ""

#: eovpn/main_window.py:208
msgid "No Network"
msgstr ""

#: eovpn/main_window.py:224
msgid "Connected"
msgstr ""

#: eovpn/main_window.py:239
msgid "Disconnect!"
msgstr ""

#: eovpn/main_window.py:312
msgid "No config selected."
msgstr ""

#: eovpn/openvpn.py:118
msgid "Authentication failed."
msgstr ""

#: eovpn/openvpn.py:121
msgid "OpenVPN Killed!"
msgstr ""

#: eovpn/openvpn.py:244
msgid "Connecting.."
msgstr ""

#: eovpn/openvpn.py:250
msgid "Config requires authorization (auth-user-pass)"
msgstr ""

#: eovpn/openvpn.py:266
msgid "Connected to {}."
msgstr ""

#: eovpn/openvpn.py:285
msgid "Disconnected."
msgstr ""

#: eovpn/openvpn.py:301
msgid "OpenVPN not found."
msgstr ""

#: eovpn/openvpn.py:385
msgid "Invalid Remote"
msgstr ""

#: eovpn/openvpn.py:390
msgid "Updating..."
msgstr ""

#: eovpn/openvpn.py:405
msgid "Config(s) updated!"
msgstr ""

#: eovpn/openvpn.py:413
msgid "No config(s) found!"
msgstr ""

#: eovpn/openvpn.py:458
msgid "Success"
msgstr ""

#: eovpn/openvpn.py:459
msgid "Valid Remote"
msgstr ""

#: eovpn/openvpn.py:460
msgid "{} OpenVPN configuration's found."
msgstr ""

#: eovpn/settings_window.py:161
msgid "Settings Saved."
msgstr ""

#: eovpn/settings_window.py:203
msgid "Settings deleted."
msgstr ""
